### ISSUE TITLE
Automatically merge double episodes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#18]
```
Based on some combination of:
 - Airdate
 - File size (compared to folder average)
 - Multiple episode numbers in filename

http://tvrename.com/bb/viewtopic.php?f=4&t=380&p=1254#p1254

```

Original issue reported on code.google.com by `tvren...@tvrename.com` on 10 Sep 2009 at 12:15

**Comment by MarkSummerville** [comment]
http://old.tvrename.com/bbold/4/t-380.html

I'm going to take a look at this....

**Comment by MarkSummerville** [comment]
Kodi uses this REGEX
https://kodi.wiki/view/Userdata/advancedsettings.xml#.3Ctvmultipartmatching.3E

**Comment by MarkSummerville** [comment]
Added function in a95ba4434cb246d98c56f94f43e0713043543cb4 to identify if the episode name may indicate that the episode is a merged one

Left to do:
1.  Look at Regex of downloaded file:
`<tvmultipartmatching>^[-_ex]+([0-9]+(?:(?:[a-i]|\\.[1-9])(?![0-9]))?)</tvmultipartmatching>`
2.  Look at filesizes of possible episode duplicates and see whether one is larger than the average in the directory:

**Comment by Andy-ABTec** [comment]
Sorry @MarkSummerville, just ran 2.3.3 RC 4 on my Library and got some broken episode names on double episodes...

Seems to work fine unless the episodes in question have different names my directory listing now contains this:

![image](https://user-images.githubusercontent.com/5175695/36268569-b698965a-126e-11e8-89cc-24b0c466d39b.png)

Happy to retest when you're ready...

**Comment by MarkSummerville** [comment]
Hi,

I think you have a few different things going on here:
1. Re RED entries. I think this is a combination of 2 new features clashing slightly. The improved naming of multi-part episodes (#106) is updating the names of the multipart episodes. At the same time the update file last updated date (#16) is trying to update the last updated date for these same file. When it gets to processing it can't find the file as (#106) has renamed them. If I'm right then retrying the full scan show remove the 'red'
2. Re Burn Notice then the `*-thumb.jpg` files are probably due to the v3 testing. We have not added this format of files in the v2 branch yet. Either that or they are the result of Kodi creating them from a library export. Try removing them and seeing whether they come back. My bet is that they won't.
3. The `*Dead Drop*` ones are probably due to old metadata. As far as I can tell from [tvdb](https://www.thetvdb.com/?tab=season&seriesid=80270&seasonid=27787&lid=7) then this is old metadata . I suspect that these have been lying around for a while. Again removing and see whether they reappear.  Ideally the system would have renamed them into the new format (and there is code that should do this, but must have failed for some reason).
4. As the system is adding thumbs for each episode there should also have been `Burn Notice - S01E11 -  Loose Ends (1)` created - can you check whether this is in there please?

*Issue*

* Looks like the system should have renamed `S01E11-E12 - Loose Ends (1) + Loose Ends (2)` into `S01E11-E12 - Loose Ends` rather than just create the new one. I'll look into this.

Cheers

**Comment by Andy-ABTec** [comment]
Sorten now thanks, deleted all the nfo files and jpgs and re-created...

Burn notice is fine too, the TVDB catalog entry has been changes to match the DVD names rather than the original episode names.,

**Comment by JoeBiellik** [comment]
@MarkSummerville Using 2.3.3 I've found a couple of edge cases:

Some shows without proper episode names just use ``Episode <num>`` as the name, if these episodes are joined then with the new code you get ``S01E01-E02 - Episode``, rather than the old ``S01E01-E02 - Episode 1 + Episode 2``.

If an episode is named like ``S01E01 - Name (Part 1)`` when merged you get ``S01E01-E02 - Name (Part``.

**Comment by MarkSummerville** [comment]
Hi @JoeBiellik - thanks for taking a look.

[this](https://github.com/TV-Rename/tvrename/blob/d09187cbf627b85afc6ad323e69916d489e69bb0/TVRename%23/TVRename/TVDoc.cs#L1123) was meant to guard against the first case. I'll take a further look, but seemed to work for mine.

I'll add somethig to look for `part`  specifically, but maybe there is some more advanced RegEx method we could use?

**Comment by MarkSummerville** [comment]
@JoeBiellik Just added an update - hopefully will solve your examples. Cheers

**Comment by JoeBiellik** [comment]
Thanks that sorted those. I think the way you have implemented it is the only real way to handle it.

The last major edge case I've seen is Roman numerals; ``... - Part I`` etc, not sure if these are outside what we want to automatically handle.

**Comment by JoeBiellik** [comment]
After rebuilding my library I've found a few more cases that need trimming:
``<show> - S01E01 - <episode>: Part 1`` -> ``<show> - S01E01-E02 - <episode>-.avi``
``<show> - S01E01 - <episode> - Part 1`` -> ``<show> - S01E01-E02 - <episode> -.avi``

There is also a strange edge case where the episode names are literally "Part x":
``<show> - S01E01 - Part 1`` & ``<show> - S01E02 - Part 2`` become ``<show> - S01E01-E02 - Episode 1.avi``, not sure the best way to handle that.

**Comment by MatLomax** [comment]
When adding a merge rule, the name gets shorter by 1 character for each file included, resulting in a filename ending in a number, e.g. `(2)`, removing characters from the end of the merged episode name by file number 5.

From digging around in the code, I've found that changing [this line](https://github.com/TV-Rename/tvrename/blob/master/TVRename%23/Utility/Helpers.cs#L833) from `fist.Length > i + 1` to `fist.Length > i` fixes the problem.

**Comment by MarkSummerville** [comment]
Thanks @MatLomax Sound like a bug to me

@JoeBiellik I think removing any `-` from the end should fix this

**Comment by MarkSummerville** [comment]
@JoeBiellik Is this right?

``<show> - S01E01 - <episode>: Part 1`` -> ``<show> - S01E01-E02 - <episode>-.avi``

I would have thought it'd be:

``<show> - S01E01 - <episode>: Part 1`` -> ``<show> - S01E01-E02 - <episode>:.avi``

**Comment by JoeBiellik** [comment]
@Mark Yes, to clarify its a colon, but becomes a dash as a colon isn't a legal file character.

**Comment by MarkSummerville** [comment]
Is see - Of course. I'll tidy it up tonight

**Comment by JoeBiellik** [comment]
@MarkSummerville I've tried your fork and all merged episode names look good, I think this is ready for 2.4.0,

**Comment by MarkSummerville** [comment]
I'm going to revisit this to:

**Proactive identification**
1.  Add multipart Regex to the filename processors:
`<tvmultipartmatching>^[-_ex]+([0-9]+(?:(?:[a-i]|\\.[1-9])(?![0-9]))?)</tvmultipartmatching>`
2. when they match then automatically add a merge rule

**Reactive identification**
3.  There is already code that looks at video length compared to others in the same folder, so this part is done. Will add a UI to show results rather than the log. For each result will give the option to quickly add a merge rule. UI will be able to select which criteria to apply

Any thoughts  / requests?

**Comment by MarkSummerville** [comment]
It is suggested everyone adds `(^|[^a-z])s?(?<s>[0-9]+).?[ex](?<e>[0-9]{2,})(-?e[0-9]{2,})*-?[ex](?<f>[0-9]{2,})[^a-z]` as their topmost FilenameProcessor or resets to defaults
