### ISSUE TITLE
Dumb(ish) question about Logging

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#198]
Silly thought...

Is there any way the NLog  config can be moved somewhere under ...App Data/TVRename (preferably with all the other config files)? That way it simplifies backup - something along the lines of: -
>  7z.exe u -r "C:\Users\<user>\Backup.zip" "C:\Users\<user>\AppData\Roaming\TVRename" 

Would backup everything and the change would also possibly removes the need to write to "Program Files(x86)\TVRename" so the security can be tightened.

**Comment by JoeBiellik** [comment]
I believe @MarkSummerville is already [working on this](https://github.com/TV-Rename/tvrename/commit/43dfc4aac7417d246268f7272bcab0cc2bd2bb94).

**Comment by MarkSummerville** [comment]
Hi @Andy-ABTec 
I don't envisage users modifying their nlog.config files which is why the program files location. Yeah sure advanced users may do so, but they can deal with permissions/security etc. As I'm not expecting changes then I don't foresee the file needing to be backed up.  (except with a new release). Just my thoughts though

**Comment by JoeBiellik** [comment]
I'm sorry, I misread the question. Mark is right however, I don't see why you would edit/backup NLog.config.

**Comment by MarkSummerville** [comment]
@Andy-ABTec  - Are you happy to close this one?

**Comment by Andy-ABTec** [comment]
Yeah, no problem, sorry I drifted back pre retirement and put my
penetration and security testing hat (grey-ish) back on for a while..

Happy Christmas!

Andy B.
