### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#224]
The top [request](http://ideas.theideawall.com/TVRename/Forum/Details/8dea3275-4010-4bab-9763-a8bb613517e0) atm is an improved UI, which I think is an excellent idea.

I have vague ideas of moving to WPF/UWP at the same time, but am not really sure of the pros/cons of this move. Could we co-exist and have two UI for a period? `Switch to beta UI` or similar mode? Any thoughts/advice are welcome. Also I thought we could use some improved components - I was hoping that we might be able to get a Telerik or DevExpress licence to speed up development, but I'm not sure that is possible. Maybe [SyncFusion](https://www.syncfusion.com/products/communitylicense)?

Overall I thought of the UI moving to look a little like [this](https://lh3.googleusercontent.com/-Lmj4NBMTU9E/Wjm_3broneI/AAAAAAADBBg/QmU_tzcKvpktb4ULhgN6nv7du0Zc7pUGQCLcBGAs/s1600/IMG_2244.JPG) - basically Icons for the tabs and each of the operations (add show, remove show etc) and move to to be horizontal tabs

Re iconography - I was going to use iconography like:
 * https://www.flaticon.com/packs/essential-set-2 or
 * https://www.iconfinder.com/iconsets/miu

Really the aim of this is to generate some discussion from a dev perspective and then we can discuss more widely on the forums

**Comment by mhurwood** [comment]
Third party components... I just don't know.

I'm not against them per-se. I've had an Infragistics Licence for work purposes for many years, because they did achieve quick UI goals with little effort, but they almost always lead to bloat and of course it means more DLLs on-top of the ones we already have.

Quite often I have found that there are often completely free extensions of existing (standard) controls that do the job I need, but don't have a million features that I don't need as well. Case in point was the "clear button inside the text box" that I put for the quick filter.

It's also clearly going to be harder to do distributed development once these 3rd party control are in place, unless we're lucky and they're on Nuget I guess. Some of the bigger packages require separate installation on the development machine, which leads me back to bloating.

I'm not saying we should totally rule it out, but it should in my opinion be a case of "we need this control because none of the standard control can do it", rather than just a case of "these replace standard controls but can be skinned more easily" or similar. A more modern UI is to be applauded, but that should be achievable mostly through standard controls.

**Comment by JoeBiellik** [comment]
I have to agree with all of @mhurwood points, however, I think it's worth clarifying between just 3rd party controls and a full 3rd party UI framework.

There is nothing wrong with our use of the [SourceGrid control](https://sourcegrid.codeplex.com/) for example, but I don't like the idea of us buying into a full framework. My experience of these has been that they lock you in and are rarely truly open source; I strongly believe we need to keep every aspect of this project as open as possible.

> Could we co-exist and have two UI for a period?

We would abstract the core functionality out of the existing UI and into a shared library within the VS solution. We can then add a new project for the new UI, consuming the shared project. This separation of core logic and UI logic would help with testing and allows us to create new projects targeting other platforms in the future (Mac UI port?). Having a single binary which can switch UI mode would be rather complex.

My personal opinion is that custom/non-standard Windows UIs are never worth it, I can't think of a single application that uses a heavily customized UI that is better for it. I'm not a fan UWP and I believe it would require a lot of work to port to this, but WPF is definitely an option. One of TV Rename's biggest pros over other similar software is its customizability and number of options. It's going to be very tricky for us to have a pretty and clean UI while keeping all our existing features and functionality.

I don't think a v3 release with an updated UI is feasible: there is too much unmaintained and undocumented code. I think v3 needs to focus primarily on refactoring existing features and improving existing flow, with a quick v4 release focusing just on the interface.

**Comment by MarkSummerville** [comment]
Good points gents. Sounds like we are starting to get a view on a roadmap to take this forward

**Comment by fotofrank** [comment]
Perhaps I don't quite understand what is ment with enhancing the UI by adding some 3rd party Controls òr a full 3rd party UI framework, but after reading the above comments this will/might involve:

- Buying Licenses for a full Pack although we need only lets say 5% of it
- Lots of extra DLLs of which we have enough already 
- Problems with distributing because of possible extra installers for the 3rd party content
- I guess rewriting lots of code, which WILL generate new unwanted bugs. 
- The loss of good working code which meanwhile you know almost from memory.

Think for a moment about these 2 wise quotes:
> "Don't try to fix it, if it ain't broken."
> "The more they over think the plumbing, the easier it is to stop up the drain."

@JoeBiellik mentioned 1 of the biggest pros of TV Rename: **customizability**!
Thinking of customizing brings me to my main question regarding an enhanced UI:

Why not keep the code just like it is and top it off with merely a UI-Skin?
The graphics are easy to create and the UI buttons would link to the existing ones within the code.
If I'm thinking correctly, this would be fairly the same as creating a Custom User Form within Excel to control different VBA procedures.

Perhaps I'm thinking way to simple about a possible solution, but I thought I'd mention it just in case.

**Comment by Andy-ABTec** [comment]
I like simple...

**Comment by StuartMeeks** [comment]
I started playing with redesigning the UI using UWP and the latest Fluent design bits and pieces. I've attached a screenshot to this comment. The only drawback is a dependency on the Windows 10 Fall Creator's Update.

I think the biggest challenge will be around extracting the logic of the current codebase from behind the windows forms classes and moving them elsewhere so I agree with @JoeBiellik on that point.

I'm no guru at design either, so I can help with the XAML but I'm no creative genius. Perhaps we need to recruit a designer who doesn't need to be a coder.

![Screenshot](https://user-images.githubusercontent.com/11793922/38327400-b86d827e-387a-11e8-9d23-83cbdc5a566c.png)

**Comment by StuartMeeks** [comment]
I've uploaded the code for the above screenshot here: [TVRename.Client](https://github.com/StuartMeeks/TVRename.Client)

**Comment by fotofrank** [comment]
@StuartMeeks 
My philosophy is: The best way to get something done is making the start to get there!

You mentioned "a dependency on the Windows 10 Fall Creator's Update". Does this mean that the GUI won't work for anybody running Windows 7 or 8?

**Comment by StuartMeeks** [comment]
It does. UWP only works on Windows 10 RTM+. You can choose the minimum patch level you want to target and the recommend patch level. It would be useful to know how many users of TVRename are pre-Windows 10 before heading down this path.

P.S. Apologies for the delay, just returned from a long business trip.

**Comment by MarkSummerville** [comment]
Hi Guys,
Sorry to miss the earlier comments. Current Stats for the website are: 
![image](https://user-images.githubusercontent.com/14905881/39350278-437b2904-4a30-11e8-8981-4edbe7967815.png)

(Which is the closest proxy for OS usage that we have)

I like the design - I'd envisaged larger LHS navigation elements though
![here](https://lh3.googleusercontent.com/-Lmj4NBMTU9E/Wjm_3broneI/AAAAAAADBBg/QmU_tzcKvpktb4ULhgN6nv7du0Zc7pUGQCLcBGAs/s1600/IMG_2244.JPG)

**Comment by StuartMeeks** [comment]
My WPF skills are ok but slow, but I'm still happy to work in it. I think our bigger hurdle is refactoring the code behind into a shared library. It would be ideal to have minimal actual business logic in the front end before we try to rebuild UI. What do you think?

**Comment by StuartMeeks** [comment]
So I've started the effort to move as much code into a separate class library. Check it out here: [dev-refactor](https://github.com/StuartMeeks/tvrename/tree/dev-refactor)

@MarkSummerville is this headed in the right direction?

**Comment by MarkSummerville** [comment]
Hi @StuartMeeks - Definitely the right direction, but the v3 branch that @JoeBiellik is running with has taken this a lot further already. It's worth you guys collaborating as you are taking the code in the same direction.

https://github.com/TV-Rename/tvrename/tree/v3

**Comment by StuartMeeks** [comment]
Hey @JoeBiellik - can you let me know how I can be of assistance?

**Comment by StuartMeeks** [comment]
Hi @MarkSummerville. I'm temporarily gone, but will return in a few days. I haven't had any response from Joe about direction or help for v3. What do you suggest? I can keep working on my repo in my spare time or just wait...

**Comment by MarkSummerville** [comment]
No worries @StuartMeeks - enjoy.

Anyone used https://github.com/ButchersBoy/MaterialDesignInXamlToolkit#Screenshots any thoughts on it with WPF? @JoeBiellik ?

**Comment by StuartMeeks** [comment]
Hi @MarkSummerville - I'd like to spend some more time working on future UI. Do you have any firm plans for that at the moment, or are you in maintenance mode?

I notice that JoeBiellik made some great progress, but seems to have dropped off the rader (and apologies, I did too). How do you want to proceed with UI?

**Comment by MarkSummerville** [comment]
No real plans other than the above. There is as much work in redefining the operations to use async tasks and being able to lock the appropriate items at the appropriate time as pure UI work. 

@JoeBiellik did a great job on the v3 branch, but we never got a to a point where we could migrate the v2 code into it. Recently I raised a ticket to try and extract whatever value/architecture from that branch into master. I'd like to incrementally work from the v2 branch so we can release bit by bit, rather than a full re-write. If there are a few of us working on it then I'd like to introduce unit testing at the same time
