### ISSUE TITLE
Serialization vs Parsing

### ISSUE THREAD

**Issue by JoeBiellik** [TV-Rename/tvrename#259]
I'm looking at making some more significant changes to processing saved settings and TVDB API results and was wondering if there is a reason parsing is used over (de)serialization?

Is using XML a legacy to when TVDB used it? Is there any reason to not move everything to JSON or another format?

**Comment by Andy-ABTec** [comment]
I'm no coder but I'll have my two penneth anway!&emsp; 😎 

I would say if its more efficient/faster simplifies other stuff and has the possibility of other benefits then go for it, but perhaps you'd better wait till we hear from Mark and maybe the others.

**Comment by MarkSummerville** [comment]
I think it was due to the tvdb providing data in xml and that xml is/was then saved. The format was the same between the downloaded file and the saved one. As long as we are able to switch between versions and deal with additional/missing attributes I don’t see any problems moving. The current setup is now good at dealing with outdated/corrupt. @mhurwood and @steevvee may have views too. 

If we refactor then there are a few bits that could/should happen too.

**Comment by MarkSummerville** [comment]
Sorry should be @sstteevvee

**Comment by MarkSummerville** [comment]
Another request if we are modifying the functionality is the ability to have settings persisted into the file without a UI to modify them. That way we can very quickly put advanced settings into the file only.  Advanced users can hand modify the file if they really need to.

**Comment by sstteevvee** [comment]
I can confirm that thetvdb used to be XML, so that data was saved (99.9% as-is) to disk.
