### ISSUE TITLE
Website Updates

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#262]
The list is actually shorter than I thought...

But  I still need to sort out the following: -

> **My Shows>Edit - Advanced**
> from "Do missing check" down - tick doesn't stay cleared 

> **My Shows>Edit - Scan Aliases**
> Can't figure out what this does, is it looking for aliases in the media library or in the source files?

> **My Shows>Search**
> Can't seem to use this for anything, am I missing something?

> **Tools>Torrent Match**
> Can't get this to work properly see #249

> **Tools>uTorrent Save To**
> Can't figure out how to use this (if it works) can pull a torrent. name from the uTorrent folder but everything else seems dead?.

I'd really like to get these sorted so I can the concentrate on the grammar readability etc

I'm happy to say "such and such is currently broken - but we are aware and will be fixing it" or whatever but I need to say something! (I've already done so once - http://www.tvrename.com/tools#folder-monitor)

Plus I don't want to say something is broken if it isn't and it's just me being thick!

**Comment by MarkSummerville** [comment]
Sorry, doing this from memory, so may be not quite right. 

1 sounds like a bug to me

2 aliases are other names given to a show. When searching then the system matches any alias. For example if you have a file called L&O:SVU s01e01.mpg it would not match “law and order special victims unit” unless you setup an alias for “L&O:SVU“. Sometimes useful for shows that have a year appended to them

I’ll have to take a look at the others once I get back

**Comment by Andy-ABTec** [comment]
Thanks Mark and apologies for disturbing you, (2) is a great help, I can go away and "fiddle" now I know what I'm looking for!

**Comment by MarkSummerville** [comment]
Re 3 - I'm not sure what you're talkign about

4,5 Dont seem to work for me. I think it is updating the priority of torrents in uTorrent. @sstteevvee  may be able to explain

**Comment by Andy-ABTec** [comment]
Re 3 - I'm talking about this window:

![image](https://user-images.githubusercontent.com/5175695/34650955-50a8430c-f3c1-11e7-8a3b-9de029154441.png)

I looks like it allows you to setup a custom search without adding the entry to "Search Engines, but I can't get it to do anything - or at least I can't figure where it's used...

**Comment by MarkSummerville** [comment]
Try  this:
1. Find a show that is in the missing list
2. Navigate to screen above
3. Click 'Use Custom Search'
4. Enter http://tvrename.com
5. Return to the missing episode and double click to autosearch

**Comment by Andy-ABTec** [comment]
Not exactly intuitive is it...

So I'm in the "Scan" tab, I've just run a scan and I have a missing file. To run a custom scan I need to go to the "My Shows" tab, right click on ANY show and select "Edit Show" to get the "Add/Edit Show" window and then select the "Search"tab. Tick the box and fill out the url, fighting with the tag names which won't even copy/paste and click "OK". Go back to the "Scan" tab, right click on a missing file and select "Search" only to discover that typed tags don't work anyway.

Ouch!

Me-thinks this would be much better if: -
a) the "Custom Search Path" was accessible by right clicking a missing file in "Scan" (maybe next to the "Search" menu entry).
b) the tags actually worked after all the painful typing.

**Comment by Andy-ABTec** [comment]
Plus it would appear that once the option has been turned on you can't turn it off...

**Comment by sstteevvee** [comment]
I think the Torrent Match and uTorrent features have been broken for a while.  There used to be things for manipulating files (and/or torrents?) based on the other.  There was also a feature that used to flag a file as missing, but downloading in uTorrent.

The custom search was to override the default search query (but not the service).  From memory I was using it on "The Daily Show", but to make it search for just "Daily Show" as the "The" wasn't in the torrent release names.  The idea was that it might also be useful for shows with a date instead of episode number in their release name.

**Comment by JoeBiellik** [comment]
From my tests the torrent features are broken; is this a feature we need to keep? Maybe it would be worth asking for the forum's opinion on if we should fix it or remove it.

I personally think the custom show search is useful, but I agree the UX is lacking. Maybe we should open a seperate issue to track it for improvement in v3?

**Comment by MarkSummerville** [comment]
" feature that used to flag a file as missing, but downloading in uTorrent." - this works great

Also I can imagine using the custom search for a show, so we can fix that up. I agree a separate ticket is the way to go

Other uTorrent features can be quarantined unless someone uses them / can get them working. I've used it and it does seem to change the priority of downloading torrents, but I'm still not sure what it's doing

**Comment by Andy-ABTec** [comment]
Do you want me to raise a ticket for the custom search?

**Comment by MarkSummerville** [comment]
It's OK, done it. I am closing as key ideas for change are rolled forward in #277 and #278

**Comment by MarkSummerville** [comment]
Created a new bug around turning off the custom search more effectively. 

I response to some comments above:
 * If you are on the 'scan' tab you can right click and 'edit show' to get straight to the show modification screen
 * Tags seem to work for me. Have you got the full `{tagName}` entered - including the braces?
 * You can remove it without hacking the XML - you just have to:
     * enable the functionality
     * delete the URL
     * THEN disable the function

#289 will make it easier to disable the functionality

I agree that the UI could do with an overhaul so that tag entry is easier, but that can wait until we do all the UI (IMHO). Further we can produce a live example to indicate what the search URL would actually look like so that any tag confusion is resolved. #278 should deliver all this.
