### ISSUE TITLE
Prevent extra network hop when moving files

### ISSUE THREAD

**Issue by IvanCharcos** [TV-Rename/tvrename#298]
Hello,

I use TVRename on my Windows machine to manage TV shows downloaded/stored by an Ubuntu network server.

I use different hard drives for downloading as well as storage.

I use UNC file paths for the files.

Is it possible to keep network traffic just within the server itself.

I believe everytime TVRename moves a file, it has to travel from the server to my Windows machine then back to the server albeit a different hard drive.

Thanks again!

**Comment by Andy-ABTec** [comment]
Hi Ivan,

You're absolutely correct, files are being pulled from your server to the Windows box and pushed back again.

The only way you could keep the traffic within the server would be for TV Rename to connect to the server and run a process that did the move which is not currently possible.

Actually strictly speaking even doing this would result in a "copy" rather than a "move" because you can't "move" across disks, move works by leaving the data where it is and modifying the directory pointer to make it look like the file is in "a different place" which it can't do with two spindles.

Sorry I'm not of more help, but can I ask why you want to restrict the traffic?

**Comment by MarkSummerville** [comment]
HI @IvanCharcos,

I'm hoping that the 2.3.1 and later versions have allowed you to see a speed increase in this area. Is that your experience? We have changed to use a better library, so the performance should be improved.  We use [AlphaFS](http://alphafs.alphaleonis.com/)

We try and move a file wherever possible rather than copy, but having said that there may be network configurations that it's not working for.

**Comment by MarkSummerville** [comment]
Hi @IvanCharcos - please see here for some discussion historically http://old.tvrename.com/bbold/4/t-457.html (but not much has changed since)

**Comment by IvanCharcos** [comment]
Hi everyone,

Copy or move, whichever method works. I currently just use the move function to move from my "Download" disk to the actual final disk and just delete the "Download" one after its done. No big deal for me.

I figured moving across SATA within the same computer is faster than moving from SATA to LAN then back to SATA. I guess its not really necessary given the speed of the disks.

**Comment by Andy-ABTec** [comment]
PLEASE DON'T QUOTE ME but there are distant rumblings about scripting possibly being available in the future, (its on the Idea Wall)

IF this does eventually appear you could possibly use it with a windows ssh client or similar to run a process on your server to do your copy/move locally.

**Comment by IvanCharcos** [comment]
How about server-side TV Rename?

Install TVRename in Linux (Ubuntu for example).
Then access frontend with a webapp or with the current GUI.

**Comment by JoeBiellik** [comment]
I don't believe the potential feature @Andy-ABTec talks about would help here.

@IvanCharcos I believe this is outside the scope of the project at the moment, however, you have a couple of possible options:

You could try running TV Rename directly on your Linux server with [Wine](https://appdb.winehq.org/objectManager.php?sClass=application&iId=2586) or Mono.

Depending on your drive configuration you could set it up in a way that tricks Windows into thinking your two physical drives in the server are a single drive. This may help.
For example, given ``/mnt/tv`` and ``/mnt/downloads`` drives you could make ``/mnt`` a SMB share. Windows sees a single network drive with two directories and, _I believe_, when Windows sends a move command SMB will perform the operation on the Linux end rather than moving the data over the network.

**Comment by IvanCharcos** [comment]
@JoeBiellik 

Huh....I will try that.. Thats a clever move if it works.

**Comment by scott-mikus** [comment]
@MarkSummerville is correct though a move only occurs when a file changes directories on the same spindle or drive. No matter the setup of you take a file and place it on another spindle you are copying the file. Same goes with making a duplicate. The only way to truly “move” a file is to have it reside as a single instance on a single spindle and move from one directory to another within that same drive or spindle. Any other type of movement is considered a copy by the file system.

I myself run tvrename on my server and log in via RDP to run the scans. Of course, I am running a windows server and not a Linux box but that way I avoid the network double copy issue you are facing. And as the other have said currently there is no way to to have tvrename simple move one file to another directory via network unless you have it setup as a SMB share and move it from one directory to another.

Long winded I know but at the moment no way around it. Either run a emulator like wine or mono or spin up a windows box to host the server. Other wise your gonna copy like crazy!

**Comment by Andy-ABTec** [comment]
That's why a scripting option with parameter passing would be so useful, you could then script a remote  connection (plink maybe?) into a linux box and run the copy process on that box (a bit like connecting with PuTTY and doing it manually)

**Comment by JoeBiellik** [comment]
@Andy-ABTec I've been playing with this idea locally. I've modified the code so that rather than performing a copy/move/delete operation locally, it invokes a command with templating support.

The problem I've found with this, or at least my quick hack, is that opening an SSH connection to my Linux file server for each file, messing around with paths and invoking the IO action locally doesn't really seem to be any faster than just working over SMB for me. Admittedly I didn't test much and was working with small files on fast drives and a fast network.

**Comment by Andy-ABTec** [comment]
Nuff said, ssh scripting can be a bit of a bugger, before I retied, expect was a common solution but I'm sure there's better ways now.

The original request was to keep the traffic within the server which this will do...

**Comment by JoeBiellik** [comment]
The scripting isn't too bad really if you know your way around the command line.

Once v3 has progressed further I'll add the feature and people can test it.

**Comment by Andy-ABTec** [comment]
Look forward to it - can make use here as well!
