### ISSUE TITLE
Regex doesn't match SHOW.s05e03.m4v

### ISSUE THREAD

**Issue by philkernick** [TV-Rename/tvrename#312]
# Expected Behaviour

I have a large number of shows that currently have the format

SHOW\SHOW.s05e03.m4v

They are not detected by the the filename processors.

# Current Behaviour

If they are named

SHOW\SHOW.s05e03.TITLE.m4v

They are detected.

I've added a very simple filename processor to show the issue:

`s(?<s>\d+)e(?<e>\d+)`

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:  Windows 10

**Comment by MarkSummerville** [comment]
Hi,

I tried a file named the way you are selecting them and it seems to work OK:

![image](https://user-images.githubusercontent.com/14905881/35775026-67326afc-09bb-11e8-9231-c28b4ce2a893.png)

maybe the issue is needing to add .m4v as an approved video type?

![image](https://user-images.githubusercontent.com/14905881/35775035-973115e6-09bb-11e8-9617-8e0e27ff4057.png)

Sorry -  need you to explain slightly more about what the issue is as it seems to be OK for me

Cheers

**Comment by philkernick** [comment]
Perfect.  That fixed it.

 

Can I suggest you add something to the Quickstart guide to say that if you are using other video extensions you need to put them in that list.

**Comment by MarkSummerville** [comment]
Yeah. We can add to the defaults. They do or probably do with a refresh

Glad it’s sorted.
