### ISSUE TITLE
10 weeks of updates?

### ISSUE THREAD

**Issue by palentir** [TV-Rename/tvrename#323]
# Expected Behaviour
First time launching program, with no appdata. Add a show and it should just search and add.

# Current Behaviour
I get a warning message with badly written english. Needs to be updated and why does it even popup for first time use? Its possible this error is because of some old files from my previous use of this program? In which case please someone explain how I start from scratch. I am trying to import my old appdata folder and I am getting exception errors. 

# Failure Information
Error text:
* We have run 10 weeks of updates but it appears the system may need to check again once this set have been processed.
* If the dates keep getting closer than keep getting 10 weeks of updates, otherwise consider a full refresh.

The first sentence should say "once this set HAS been processed".
The 2nd sentence I can't even decode what that means.

## Steps to Reproduce
Delete %appdata%\TVRename\TVRename
Add a new show
When I scan it gets stuck on 99% too. I might have to go back to version 2.1 because that at least worked.

**Comment by JoeBiellik** [comment]
Thanks for reporting this, this may be a bug I've seen but not yet reported. I believe this is a bug in the new TVDB API handling when the entire library only contains shows which have not been updated in the last 10 weeks.

Has the show you tried adding finished airing (i.e. no more future episodes)? Please try adding a currently running show as well as your original, and see if that fixes it.

**Comment by MarkSummerville** [comment]
Hi @palentir,
Do the dates reported in the error message keep getting later? If so that means the system is catching up in 10 week blocks. This is a limitation of the new TVDB.COM interface that updates are only available in [week blocks](https://api.thetvdb.com/swagger#!/Updates/get_updated_query).  I think @JoeBiellik  is correct and you will find that you have added a show that has not been updated in some time. 

You mention that it gets stuck on 99% - I'd advise looking in the error log and reporting back any issues you see in there. That may help us get to the bottom of that issue.

*Solutions*
 * After a few iterations it will get back in sync. 
 * If you don't wish to wait, there is a [workaround in the Forum](https://groups.google.com/forum/#!topic/tvrename/31J1LfLmPWw). 
 * The error message also reports a way around your issue and that is to do a 'Force Refresh All' This will bring you back in-sync too.

*Outcomes*
* Update the second sentence of the error message to make it clearer.
* Review code to cater for this edge case. We are very cautious about updating the 'lastupdated' date without ensuring we have not  [missed any updates](https://github.com/TV-Rename/tvrename/blob/6bec0debdb5c96aab27027bbe1a778480cb04a8d/TVRename%23/TheTVDB/TheTVDB.cs#L717), but in this case there is possibly more we could do.

You are welcome to go back to 2.1, but it uses the older XML style interface with thetvdb.com and that is no longer supported. There are an number of reports on the forums that people are starting to have issue with older versions.

**Comment by JoeBiellik** [comment]
@MarkSummerville There is either a bug or some bad logic at play here. If you wipe your settings add [Tom and Jerry](https://www.thetvdb.com/?tab=series&id=72860) and then hit refresh you get:

![image](https://user-images.githubusercontent.com/43646/35953671-a0e27264-0c7d-11e8-84d1-529792ea4c41.png)

I could refresh 100 times but this seems unnecessary. The show was just added so it must be up to date, there should be no need to process the TVDB update feed before when it was added. Can we just check if the last update time is undefined at set it to now?

**Comment by MarkSummerville** [comment]
I think the solution is just to set the update time for a fresh install to be `now`. Any added show will get the latest version of that show. It will certainly solve this use case, I don't think it'll cause anymore problems, but not sure that there are not other scenarios in the there.

**Comment by JoeBiellik** [comment]
This isn't specific just for new installs though. From my understanding, when adding a show we keep the update timestamp TVDB sends, but that will just cause unnecessary updates; as we just got the latest version, it should be safe to set update timestamp to now. My knowledge of the v2 code is lacking but can't adding a show be treated like force refreshing it?

**Comment by MarkSummerville** [comment]
We have a global 'last updated' timestamp and ask TVDB for updates since that time. That's the way the TVDB update interface works.  We don't ask for each show what the last update time was and then process the show. It works the other way. We ask TVDB for shows that have updated since x and then look through that list of updates for shows we are interested in.

**Comment by JoeBiellik** [comment]
Yes, sorry to be clear, when adding a show how is the last updated timestamp being changed? Adding a show should never effect that timestamp? From my screenshot above, 1970 is from the ``null DateTime`` but where is the 2011 coming from?

**Comment by MarkSummerville** [comment]
Strictly the 'add show' only adds the show, it then sets itself to `dirty` which means that the background download picks it up and gets any missing episodes via the `GetUpdates` method. 

The end of the `GetUpdates` method calculates what the correct new update time should be. In this case this is the max(updateTime) of the obtained updates. When you ask for TVDB for 10 weeks of updates starting from `null datetime` the max update time of the resultant set is that 2011 date.

To complicate things there are `New_Srv_Time` and `Srv_Time` which are subtly different.

**Comment by MarkSummerville** [comment]
Closing as we have a fix in place planned for 2.3.3 final
