### ISSUE TITLE
Airs in Timezone for show keeps resetting to default

### ISSUE THREAD

**Issue by fotofrank** [TV-Rename/tvrename#344]
- [x] I am running the latest [2.3.3](https://github.com/TV-Rename/tvrename/releases)
- [x] I checked to make sure that this issue has not already been [filed](https://github.com/TV-Rename/tvrename/issues)
- [x] I checked the [documentation](http://www.tvrename.com/userguide) / [support forum](https://groups.google.com/forum/#!forum/tvrename) and found no answer
- [x] It is a bug (i.e. something that is going wrong) and not a new feature (These should be raised on the [Idea Wall](http://ideas.theideawall.com/TVRename/Forum/Details/8dea3275-4010-4bab-9763-a8bb613517e0))

# Expected Behaviour

1. Set a Shows "Airs in Timezone" to Western Europe Standard time.
2. Save & Closing TVRename
3. Open TVRename
4. The Shows "Airs in Timezone" is Western Europe Standard time AND the episodes airdates are correct.

# Current Behaviour

1. Set a Shows "Airs in Timezone" to Western Europe Standard time.
2. Save & Closing TVRename
3. Open TVRename
4. The Shows "Airs in Timezone" is at the default setting AND the episodes airdates are 1 day off again

# Failure Information
This bug was NOT present in v2.3.2

* Operating System: Windows 7 x64

**Comment by MarkSummerville** [comment]
Thanks for reporting. Seems to be something funny going on with TimeZones:
* They are currently stored in the TVDB Cache rather than in the settings file

For me, if I:
1. Set a Shows "Airs in Timezone" to Western Europe Standard time.
2. Save & Closing TVRename
3. Open TVRename
4. The Shows "Airs in Timezone" is Western Europe Standard time.
(ie it works OK)

However I have to save the settings manually and make sure the TVDB cache is saved.

Also if you blow away the TVDB cache then it throws away your custom timezones that seems illogical to me.
