### ISSUE TITLE
Add Idx as subtitle extension

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#442]
and make it user configurable:
https://groups.google.com/forum/#!topic/tvrename/qeffXukIeOM

**Comment by MarkSummerville** [comment]
Modify IsLanguageSpecificSubtitle in FileHelper

**Comment by Andy-ABTec** [comment]
Please let me know where in "Options" the configuration "is" when you're done, I'll need to update the docs...

**Comment by MarkSummerville** [comment]
@Andy-ABTec  On a new 'subtitles' tab that gathers together all the subtitle stuff together

**Comment by Andy-ABTec** [comment]
OK, thanks...

Just pulled "master" from tvrename/tvrename and built it, not seeing the new tab, amI missing something (I usually am!)

**Comment by MarkSummerville** [comment]
![image](https://user-images.githubusercontent.com/14905881/42296318-edd97046-8026-11e8-8c88-96085a2a0f75.png)

I'll do a build and put out another RC which will have it in.

**Comment by Andy-ABTec** [comment]
Cool, apologies for the confusion...

**Comment by localhost61** [comment]
Great ! It was a feature I was looking for too. I suspect some subtitles to have previously disappeared after TVRename due to loss of the language coded extension.
Now, I tested the latest release 2.4.3.RC4 and it works.
"myShow - S01E04.EN.srt"  together with 
"myShow - S01E04.SP.srt" were properly renamed
"myShow - S01E04 - Episode title.EN.srt" and
"myShow - S01E04 - Episode title.SP.srt"
Kudos !

**Comment by Andy-ABTec** [comment]
The beta site now has updated docs...

Please can you check the other options to make sure I haven't missed any "removal" tweaks.

**Comment by MarkSummerville** [comment]
Beta site looks good
Great work
