### ISSUE TITLE
Shows Not Renaming

### ISSUE THREAD

**Issue by cSooy417** [TV-Rename/tvrename#624]
# Expected Behaviour

When I click scan it should rename and move my episodes.

# Current Behaviour

For 2 shows (The Grand Tour (2016) and The Magicians (2015)) it is asking me to add the shows even though they are already added and it has sorted them in the past. If I "add" them it still doesn't sort the new episodes. All of my other shows are working fine.

* Operating System: WIndows 10
* Are you using the windows version or command line version? Windows

**Comment by MarkSummerville** [comment]
Can you take a look in the logs?

Have you created aliases for the shows?

**Comment by MarkSummerville** [comment]
To expand then creating an alias or custom show name for "The grand tour (2016)" to be "The grand tour" should help (assuming you don't have the "(2016)" part in the title)

**Comment by Andy-ABTec** [comment]
I have a sneaking suspicion that, for the Magicians at least.... the issue is with the show name.

It's called "The Magicians"
thetvdb.com knows it as "The Magicians (2015)"
The torrent sites know it as "The Magicians US" most of the time...

Might not be the root of the problem but it's certainly not helping!

**Comment by cSooy417** [comment]
Aliasing worked. Odd that it was working fine and stopped.
