### ISSUE TITLE
another bug in alpha 27

### ISSUE THREAD

**Issue by SAH7777** [TV-Rename/tvrename#793]
bulk add shows > click add > map empty folder with " (testing)" suffix in its folder name as a 'top' media library folder > click Check > see bug... TV Rename tries to add the 'top' media library folder as a TV Show

plz can u fix when able, thx

**Comment by SirSparkles** [comment]
That is expected behaviour. Bulk add shows looks for any folder with no subfolders (or only 'Season xx' subfolders) and assumes this folder should contain files.

If you want it to only consider folders that have files in them, set the following parameter:
![image](https://user-images.githubusercontent.com/14905881/121915311-ae06bc00-cd65-11eb-9263-1adae54d99d0.png)

**Comment by SAH7777** [comment]
ah ha! thx!
