### ISSUE TITLE
Updated to the latest version and I can no longer rename TV shows

### ISSUE THREAD

**Issue by MarioRossiGithub** [TV-Rename/tvrename#973]
As described in the title, I just downloaded the latest version (4.9.9) but I can no longer rename TV shows.
Usually I add a TV show through the "Add" button, then I set the TMDB code, the base folder and a custom naming format. Then I click on "Scan <tv show name>" and it automatically finds all episodes and the correct title.
Now if I scan I only get a blank page with only the name of the seasons:
![Immagine](https://github.com/TV-Rename/tvrename/assets/65786150/2af8560c-9598-40d4-93a3-2524ca7d4c95)

I tried everything to fix the problem. What do I have to do?
Thanks

**Comment by TommySnyder** [comment]
I'm just a little confused at what your problem is.  Is it that you only see the seasons and not the individual episodes?
If so, you need to UNcheck the "Group Entire Seasons of Missing Episodes" in Scan Settings in Preferences.

![Screenshot 2023-06-27 5 31 26 PM](https://github.com/TV-Rename/tvrename/assets/108505954/aa06d253-5ba1-4095-af38-742a44ac483a)

**Comment by SirSparkles** [comment]
Right click on the group item in the search results then "revert to missing episodes"

**Comment by MarioRossiGithub** [comment]
Thank you. This only partially solves my problem. Now I have the list of all episodes but I cannot check the episodes because it doesn't find the correct corresponding source file:
![Immagine](https://github.com/TV-Rename/tvrename/assets/65786150/817e8f87-f3d4-40c3-9371-771e8ecdead9)

**Comment by TommySnyder** [comment]
Could you show an example or two of your Breaking Bad source filenames?  More, if there are more variations.  Are your source files found in one of the Search Folders listed in Options -> Preferences -> Search Folders?  If possible, could you attach a screenshot of the Search Folders window?  Also, a screenshot of your Filename Processors window, found at Options -> Filename Processors would be very helpful.

**Comment by MarioRossiGithub** [comment]
Of course.
![Immagine3](https://github.com/TV-Rename/tvrename/assets/65786150/ac275aa1-e040-4bd4-9aa3-3e574a6a56fc)

![immagine](https://github.com/TV-Rename/tvrename/assets/65786150/9eeb48e4-407e-472c-bbe7-6d8c60fe0111)

![Immagine](https://github.com/TV-Rename/tvrename/assets/65786150/b5fb3462-ab60-48d8-99e5-428df1f358bd)

I don't have any folder in the Search Folders section in preferences because I set the folder in the specific tv show settings.
![immagine](https://github.com/TV-Rename/tvrename/assets/65786150/3bd5b424-5cb1-4f8a-9afc-339a1de8b8dc)

Filename Processors
![Immagine2](https://github.com/TV-Rename/tvrename/assets/65786150/fe663e56-0bdb-4143-b20d-f11914fac0ff)

**Comment by TommySnyder** [comment]
Your main problem appears to be that none of the Filename Processors (including the disabled ones) will match the format of your source files.  In my opinion you'll have to modify the source files to match one of the processors or write a new Regex and add that in.  The former is the easier.  With the examples you showed, I would do a find and replace (multi-file preferably) and change the "Ep " (note the space) to "Breaking Bad (2008)_S01E" and it would match with the second one down on your Processor list.
I'm, personally, confused about how you are entering your source files.  Since you don't use Search Folders, do you place the files right in the library folders and do a Bulk Add.  I always use Search Folders and so I'm not really familiar with any other method of entering the source files.  Perhaps @SirSparkles could take it from here because I'm really out of my element with anything other than Search Folders.

**Comment by MarioRossiGithub** [comment]
Thank you, while I was posting the screenshots I imagined that was the problem. I'll try to fix it in some way.
In any case, to clarify I just have all my tv shows folders in a specific directory, then I add the tv show in TV Rename and browse to the specific tv show folder. Then scan. This is the way I do it normally.
I take the opportunity to ask a question about custom episode naming. Is there a way to set a custom naming format for **all** shows (and not do it everytime in every tv show settings)?

**Comment by TommySnyder** [comment]
Options -> Filename Template Editor
[https://www.tvrename.com/manual/options/#filename-template-editor](url)

**Comment by MarioRossiGithub** [comment]
Thank you very much
