### ISSUE TITLE
Scanner in version 5.08 doesn't work at all.

### ISSUE THREAD

**Issue by daplon** [TV-Rename/tvrename#995]
Scanner in version 5.08 doesn't work at all.

If I want to scan a series recently added to the collection, it takes a long time and freezes.
Looking at the log, you can see how it makes requests to TheTVDB's v4 API and only gets 500 responses indefinitely.

If it freezes, you can only close the program through the task manager.

I've been using Win 10 and this program for years and have never had any problems with it.

Reinstalling it and cleaning the configuration files has not worked.

Any solution?

I add a log file and another with my configuration

[Bug Report File.txt](https://github.com/TV-Rename/tvrename/files/13401126/Bug.Report.File.txt)
[TVRename.log](https://github.com/TV-Rename/tvrename/files/13401127/TVRename.log)

**Comment by TommySnyder** [comment]
These lines of your log tells a lot of the story -

2023-11-18 18:38:47|INFO| Loaded file with updates until 24/09/2023 18:45:20 
2023-11-18 18:54:12|INFO| TV Rename free again (busy since 18/11/2023 18:49:15) 

You gave TVRename 5 minutes to gather up all the additional updates made to TVDB from Sept. 24th to Nov. 18th and then you aborted out.  In that stretch of time thousands of updates were made.  In those 5 minutes you were only able to process updates up until Sept. 27th.  You still had 1-3/4 months to go.  If you aren't going to keep TVRename updated on a regular basis of, at least, once a week, then you need to show some patience.  Start the process and walk away and find something around the house to do for a little while.  The other option would be to do a Forced Refresh All before the Scan.  That might make the time to get all the updates a tiny bit less because it brings down all the information new rather than bringing down the updates based on date and having to fit it in with existing information in your database.

**Comment by daplon** [comment]
Thank you very much !!! 

I used the 5 min thing as an example. I actually had it for like 25 min one day and I thought it didn't work.

What worked was to force refresh everything.
